from pydantic import BaseModel, Field
from typing import List, Optional

class ChatMessageRequest(BaseModel):
    message: str = Field(
        ...,
        description="The chat message input sent by the user.",
        examples=["I lost money in a UPI scam"]
    )
    session_id: str = Field(
        ...,
        description="Unique identifier for the conversational session.",
        examples=["session-123"]
    )

class ChatMessageResponse(BaseModel):
    reply: str = Field(
        ...,
        description="Conversational reply generated by the Groq AI.",
        examples=["I'm sorry to hear that. Can you please share the amount lost?"]
    )
    session_id: str = Field(
        ...,
        description="Session identifier associated with this response."
    )

class FraudReportSchema(BaseModel):
    # 1. Victim Details Block
    victim_name: Optional[str] = Field(None, description="Full name of the victim.")
    victim_phone: Optional[str] = Field(None, description="Primary contact phone number.")
    victim_alternate_phone: Optional[str] = Field(None, description="Alternate contact phone number.")
    victim_email: Optional[str] = Field(None, description="Email ID.")
    victim_aadhaar: Optional[str] = Field(None, description="Aadhaar Card Number of the victim.")
    victim_gender: Optional[str] = Field(None, description="Gender (e.g. Male, Female, Other).")
    victim_dob: Optional[str] = Field(None, description="Date of birth (DD/MM/YYYY).")
    victim_address: Optional[str] = Field(None, description="Address details.")
    victim_city: Optional[str] = Field(None, description="City.")
    victim_state: Optional[str] = Field(None, description="State.")
    victim_pincode: Optional[str] = Field(None, description="Pincode.")

    # 2. Incident Details Block
    date_of_fraud: Optional[str] = Field(None, description="Date of the fraud transaction.")
    time_of_fraud: Optional[str] = Field(None, description="Time of the fraud transaction.")
    scam_category: Optional[str] = Field(None, description="Type of fraud category (e.g. 'UPI Fraud', 'Digital Arrest Scam', etc.).")
    incident_description: Optional[str] = Field(None, description="Concise summary of the scam event / fraud description.")
    amount_lost: Optional[float] = Field(None, description="Total monetary loss in INR.")
    was_money_deducted: Optional[str] = Field(None, description="Was money deducted? Yes or No.")

    # 3. Fraudster Details (Communication)
    fraudster_phone: Optional[str] = Field(None, description="Fraudster contact phone number.")
    fraudster_email: Optional[str] = Field(None, description="Fraudster email address.")
    fraudster_description: Optional[str] = Field(None, description="Fraudster description at the time of the scam.")
    website_link: Optional[str] = Field(None, description="Scam website links.")
    social_media_account: Optional[str] = Field(None, description="Scammer social media accounts.")
    whatsapp_number: Optional[str] = Field(None, description="Fraudster WhatsApp number.")
    telegram_id: Optional[str] = Field(None, description="Fraudster Telegram handle.")

    # 4. Bank & Payment Details
    bank_name: Optional[str] = Field(None, description="Name of victim's bank.")
    account_number: Optional[str] = Field(None, description="Victim's bank account number.")
    upi_id: Optional[str] = Field(None, description="Victim's UPI ID used for payment.")
    payment_app_used: Optional[str] = Field(None, description="Payment application used (e.g., PhonePe, GPay, Paytm).")
    transaction_id: Optional[str] = Field(None, description="Transaction ID or Reference Number.")
    transaction_date: Optional[str] = Field(None, description="Date of transaction.")
    transaction_amount: Optional[float] = Field(None, description="Amount of the transaction.")
    receiver_upi_id: Optional[str] = Field(None, description="Receiver or Scammer's UPI ID / Bank Account.")

    # 6. Device Information Block
    device_mobile_number: Optional[str] = Field(None, description="Mobile number used on the device.")
    device_type: Optional[str] = Field(None, description="Device Type (e.g., Android, iOS, Windows).")
    device_brand_model: Optional[str] = Field(None, description="Device brand or model (e.g. Realme 8, iPhone 13).")
    device_ip: Optional[str] = Field(None, description="IP Address of the device if known.")
    installed_suspicious_app: Optional[str] = Field(None, description="Did you install a suspicious app? Yes or No.")
    any_remote_access_app: Optional[str] = Field(None, description="Was any remote access app like AnyDesk used? Yes or No.")

    # 7. Complaint Status Block
    reported_to_bank: Optional[str] = Field(None, description="Reported to Bank? Yes or No.")
    bank_reference_no: Optional[str] = Field(None, description="Bank Reference or Complaint No.")
    called_1930: Optional[str] = Field(None, description="Called national hotline 1930? Yes or No.")
    ticket_1930_id: Optional[str] = Field(None, description="1930 Ticket ID reference.")
    complaint_submitted_i4c: Optional[str] = Field(None, description="Complaint submitted on I4C Portal? Yes or No.")

    # Timeline Reconstruction
    timeline_events: Optional[List[str]] = Field(default=[], description="Reconstructed chronological timeline of events.")

    # Meta parameters
    scammer_identifiers: List[str] = Field(default=[], description="Extracted scanner UPIs or accounts.")
    is_complete: bool = Field(False, description="Set to true if all critical fields (Name, Phone, Category, Amount, Date) are successfully gathered.")
    missing_fields: List[str] = Field(default=[], description="List of core parameters still missing.")
